// --- Enums ------------------------------------

/**
 * @typedef {'af'|'al'|'dz'|'ad'|'ao'|'ag'|'ar'|'am'|'au'|'at'|'az'|'bs'|'bh'|'bd'|'bb'|'by'|'be'|'bz'|'bj'|'bt'|'bo'|'ba'|'bw'|'br'|
 *  'bn'|'bg'|'bf'|'bi'|'cv'|'kh'|'cm'|'ca'|'cf'|'td'|'cl'|'cn'|'co'|'km'|'cg'|'cr'|'hr'|'cu'|'cy'|'cz'|'cd'|'dk'|'dj'|'dm'|'do'|'ec'|
 *  'eg'|'sv'|'gq'|'er'|'ee'|'sz'|'et'|'fj'|'fi'|'fr'|'ga'|'gm'|'ge'|'de'|'gh'|'gr'|'gd'|'gt'|'gn'|'gw'|'gy'|'ht'|'hn'|'hu'|'is'|
 *  'in'|'id'|'ir'|'iq'|'ie'|'il'|'it'|'jm'|'jp'|'jo'|'kz'|'ke'|'ki'|'kw'|'kg'|'la'|'lv'|'lb'|'ls'|'lr'|'ly'|'li'|'lt'|'lu'|'mg'|
 *  'mw'|'my'|'mv'|'ml'|'mt'|'mh'|'mr'|'mu'|'mx'|'fm'|'md'|'mc'|'mn'|'me'|'ma'|'mz'|'mm'|'na'|'nr'|'np'|'nl'|'nz'|'ni'|'ne'|'ng'|
 *  'kp'|'mk'|'no'|'om'|'pk'|'pw'|'pa'|'pg'|'py'|'pe'|'ph'|'pl'|'pt'|'qa'|'ro'|'ru'|'rw'|'kn'|'lc'|'vc'|'ws'|'sm'|'st'|'sa'|'sn'|
 *  'rs'|'sc'|'sl'|'sg'|'sk'|'si'|'sb'|'so'|'za'|'kr'|'ss'|'es'|'lk'|'sd'|'sr'|'se'|'ch'|'sy'|'tj'|'tz'|'th'|'tl'|'tg'|'to'|'tt'|
 *  'tn'|'tr'|'tm'|'tv'|'ug'|'ua'|'ae'|'gb'|'us'|'uy'|'uz'|'vu'|'va'|'ve'|'vn'|'ye'|'zm'|'zw'} Country
 * @typedef {'nzd'|'aud'|'usd'|'gbp'|'btc'|'aed'|'ars'|'bdt'|'bhd'|'brl'|'cad'|'chf'|'clp'|'cny'|'cop'|'czk'|'dkk'|'egp'|'eur'|
 *  'hkd'|'huf'|'idr'|'ils'|'inr'|'jod'|'jpy'|'kes'|'krw'|'kwd'|'lkr'|'mad'|'mxn'|'myr'|'ngn'|'nok'|'omr'|'pen'|'php'|'pkt'|
 *  'pln'|'qar'|'ron'|'rub'|'sar'|'sek'|'sgd'|'thb'|'try'|'twd'|'uah'|'vnd'|'zar'} Currency
 */

/** @type {{ [key in Currency]: { name: string, symbol: string, digits: number } }} */
export const currencies = {
  nzd: { name: 'New Zealand Dollar', symbol: '$', digits: 2 },
  aud: { name: 'Australian Dollar', symbol: '$', digits: 2 },
  usd: { name: 'US Dollar', symbol: '$', digits: 2 },
  gbp: { name: 'Great Britain Pound', symbol: '£', digits: 2 },
  btc: { name: 'Bitcoin', symbol: '₿', digits: 8 },
  aed: { name: 'UAE Dirham', symbol: 'د.إ', digits: 2 },
  ars: { name: 'Argentine Peso', symbol: '$', digits: 2 },
  bdt: { name: 'Bangladeshi Taka', symbol: '৳', digits: 2 },
  bhd: { name: 'Bahraini Dinar', symbol: '.د.ب', digits: 3 },
  brl: { name: 'Brazilian Real', symbol: 'R$', digits: 2 },
  cad: { name: 'Canadian Dollar', symbol: '$', digits: 2 },
  chf: { name: 'Swiss Franc', symbol: 'Fr', digits: 2 },
  clp: { name: 'Chilean Peso', symbol: '$', digits: 0 },
  cny: { name: 'Chinese Yuan', symbol: '¥', digits: 2 },
  cop: { name: 'Colombian Peso', symbol: '$', digits: 2 },
  czk: { name: 'Czech Koruna', symbol: 'Kč', digits: 2 },
  dkk: { name: 'Danish Krone', symbol: 'kr', digits: 2 },
  egp: { name: 'Egyptian Pound', symbol: '£', digits: 2 },
  eur: { name: 'Euro', symbol: '€', digits: 2 },
  hkd: { name: 'Hong Kong Dollar', symbol: '$', digits: 2 },
  huf: { name: 'Hungarian Forint', symbol: 'Ft', digits: 0 },
  idr: { name: 'Indonesian Rupiah', symbol: 'Rp', digits: 0 },
  ils: { name: 'Israeli Shekel', symbol: '₪', digits: 2 },
  inr: { name: 'Indian Rupee', symbol: '₹', digits: 2 },
  jod: { name: 'Jordanian Dinar', symbol: 'د.ا', digits: 3 },
  jpy: { name: 'Japanese Yen', symbol: '¥', digits: 0 },
  kes: { name: 'Kenyan Shilling', symbol: 'Sh', digits: 2 },
  krw: { name: 'South Korean Won', symbol: '₩', digits: 0 },
  kwd: { name: 'Kuwaiti Dinar', symbol: 'د.ك', digits: 3 },
  lkr: { name: 'Sri Lankan Rupee', symbol: 'Rs', digits: 2 },
  mad: { name: 'Moroccan Dirham', symbol: 'د.م.', digits: 2 },
  mxn: { name: 'Mexican Peso', symbol: '$', digits: 2 },
  myr: { name: 'Malaysian Ringgit', symbol: 'RM', digits: 2 },
  ngn: { name: 'Nigerian Naira', symbol: '₦', digits: 2 },
  nok: { name: 'Norwegian Krone', symbol: 'kr', digits: 2 },
  omr: { name: 'Omani Rial', symbol: '﷼', digits: 3 },
  pen: { name: 'Peruvian Sol', symbol: 'S/', digits: 2 },
  php: { name: 'Philippine Peso', symbol: '₱', digits: 2 },
  pkt: { name: 'Pakistani Rupee', symbol: '₨', digits: 2 },
  pln: { name: 'Polish Zloty', symbol: 'zł', digits: 2 },
  qar: { name: 'Qatari Riyal', symbol: '﷼', digits: 2 },
  ron: { name: 'Romanian Leu', symbol: 'lei', digits: 2 },
  rub: { name: 'Russian Ruble', symbol: '₽', digits: 2 },
  sar: { name: 'Saudi Riyal', symbol: '﷼', digits: 2 },
  sek: { name: 'Swedish Krona', symbol: 'kr', digits: 2 },
  sgd: { name: 'Singapore Dollar', symbol: '$', digits: 2 },
  thb: { name: 'Thai Baht', symbol: '฿', digits: 2 },
  try: { name: 'Turkish Lira', symbol: '₺', digits: 2 },
  twd: { name: 'New Taiwan Dollar', symbol: 'NT$', digits: 2 },
  uah: { name: 'Ukrainian Hryvnia', symbol: '₴', digits: 2 },
  vnd: { name: 'Vietnamese Dong', symbol: '₫', digits: 0 },
  zar: { name: 'South African Rand', symbol: 'R', digits: 2 },
}

/** @type {{ [key in Country]: { name: string } }} */
export const countries = {
  af: { name: 'Afghanistan' },
  al: { name: 'Albania' },
  dz: { name: 'Algeria' },
  ad: { name: 'Andorra' },
  ao: { name: 'Angola' },
  ag: { name: 'Antigua and Barbuda' },
  ar: { name: 'Argentina' },
  am: { name: 'Armenia' },
  au: { name: 'Australia' },
  at: { name: 'Austria' },
  az: { name: 'Azerbaijan' },
  bs: { name: 'Bahamas' },
  bh: { name: 'Bahrain' },
  bd: { name: 'Bangladesh' },
  bb: { name: 'Barbados' },
  by: { name: 'Belarus' },
  be: { name: 'Belgium' },
  bz: { name: 'Belize' },
  bj: { name: 'Benin' },
  bt: { name: 'Bhutan' },
  bo: { name: 'Bolivia' },
  ba: { name: 'Bosnia and Herzegovina' },
  bw: { name: 'Botswana' },
  br: { name: 'Brazil' },
  bn: { name: 'Brunei' },
  bg: { name: 'Bulgaria' },
  bf: { name: 'Burkina Faso' },
  bi: { name: 'Burundi' },
  cv: { name: 'Cabo Verde' },
  kh: { name: 'Cambodia' },
  cm: { name: 'Cameroon' },
  ca: { name: 'Canada' },
  cf: { name: 'Central African Republic' },
  td: { name: 'Chad' },
  cl: { name: 'Chile' },
  cn: { name: 'China' },
  co: { name: 'Colombia' },
  km: { name: 'Comoros' },
  cg: { name: 'Congo (Congo-Brazzaville)' },
  cr: { name: 'Costa Rica' },
  hr: { name: 'Croatia' },
  cu: { name: 'Cuba' },
  cy: { name: 'Cyprus' },
  cz: { name: 'Czechia' },
  cd: { name: 'Democratic Republic of the Congo' },
  dk: { name: 'Denmark' },
  dj: { name: 'Djibouti' },
  dm: { name: 'Dominica' },
  do: { name: 'Dominican Republic' },
  ec: { name: 'Ecuador' },
  eg: { name: 'Egypt' },
  sv: { name: 'El Salvador' },
  gq: { name: 'Equatorial Guinea' },
  er: { name: 'Eritrea' },
  ee: { name: 'Estonia' },
  sz: { name: 'Eswatini' },
  et: { name: 'Ethiopia' },
  fj: { name: 'Fiji' },
  fi: { name: 'Finland' },
  fr: { name: 'France' },
  ga: { name: 'Gabon' },
  gm: { name: 'Gambia' },
  ge: { name: 'Georgia' },
  de: { name: 'Germany' },
  gh: { name: 'Ghana' },
  gr: { name: 'Greece' },
  gd: { name: 'Grenada' },
  gt: { name: 'Guatemala' },
  gn: { name: 'Guinea' },
  gw: { name: 'Guinea-Bissau' },
  gy: { name: 'Guyana' },
  ht: { name: 'Haiti' },
  hn: { name: 'Honduras' },
  hu: { name: 'Hungary' },
  is: { name: 'Iceland' },
  in: { name: 'India' },
  id: { name: 'Indonesia' },
  ir: { name: 'Iran' },
  iq: { name: 'Iraq' },
  ie: { name: 'Ireland' },
  il: { name: 'Israel' },
  it: { name: 'Italy' },
  jm: { name: 'Jamaica' },
  jp: { name: 'Japan' },
  jo: { name: 'Jordan' },
  kz: { name: 'Kazakhstan' },
  ke: { name: 'Kenya' },
  ki: { name: 'Kiribati' },
  kw: { name: 'Kuwait' },
  kg: { name: 'Kyrgyzstan' },
  la: { name: 'Laos' },
  lv: { name: 'Latvia' },
  lb: { name: 'Lebanon' },
  ls: { name: 'Lesotho' },
  lr: { name: 'Liberia' },
  ly: { name: 'Libya' },
  li: { name: 'Liechtenstein' },
  lt: { name: 'Lithuania' },
  lu: { name: 'Luxembourg' },
  mg: { name: 'Madagascar' },
  mw: { name: 'Malawi' },
  my: { name: 'Malaysia' },
  mv: { name: 'Maldives' },
  ml: { name: 'Mali' },
  mt: { name: 'Malta' },
  mh: { name: 'Marshall Islands' },
  mr: { name: 'Mauritania' },
  mu: { name: 'Mauritius' },
  mx: { name: 'Mexico' },
  fm: { name: 'Micronesia' },
  md: { name: 'Moldova' },
  mc: { name: 'Monaco' },
  mn: { name: 'Mongolia' },
  me: { name: 'Montenegro' },
  ma: { name: 'Morocco' },
  mz: { name: 'Mozambique' },
  mm: { name: 'Myanmar' },
  na: { name: 'Namibia' },
  nr: { name: 'Nauru' },
  np: { name: 'Nepal' },
  nl: { name: 'Netherlands' },
  nz: { name: 'New Zealand' },
  ni: { name: 'Nicaragua' },
  ne: { name: 'Niger' },
  ng: { name: 'Nigeria' },
  kp: { name: 'North Korea' },
  mk: { name: 'North Macedonia' },
  no: { name: 'Norway' },
  om: { name: 'Oman' },
  pk: { name: 'Pakistan' },
  pw: { name: 'Palau' },
  pa: { name: 'Panama' },
  pg: { name: 'Papua New Guinea' },
  py: { name: 'Paraguay' },
  pe: { name: 'Peru' },
  ph: { name: 'Philippines' },
  pl: { name: 'Poland' },
  pt: { name: 'Portugal' },
  qa: { name: 'Qatar' },
  ro: { name: 'Romania' },
  ru: { name: 'Russia' },
  rw: { name: 'Rwanda' },
  kn: { name: 'Saint Kitts and Nevis' },
  lc: { name: 'Saint Lucia' },
  vc: { name: 'Saint Vincent and the Grenadines' },
  ws: { name: 'Samoa' },
  sm: { name: 'San Marino' },
  st: { name: 'Sao Tome and Principe' },
  sa: { name: 'Saudi Arabia' },
  sn: { name: 'Senegal' },
  rs: { name: 'Serbia' },
  sc: { name: 'Seychelles' },
  sl: { name: 'Sierra Leone' },
  sg: { name: 'Singapore' },
  sk: { name: 'Slovakia' },
  si: { name: 'Slovenia' },
  sb: { name: 'Solomon Islands' },
  so: { name: 'Somalia' },
  za: { name: 'South Africa' },
  kr: { name: 'South Korea' },
  ss: { name: 'South Sudan' },
  es: { name: 'Spain' },
  lk: { name: 'Sri Lanka' },
  sd: { name: 'Sudan' },
  sr: { name: 'Suriname' },
  se: { name: 'Sweden' },
  ch: { name: 'Switzerland' },
  sy: { name: 'Syria' },
  tj: { name: 'Tajikistan' },
  tz: { name: 'Tanzania' },
  th: { name: 'Thailand' },
  tl: { name: 'Timor-Leste' },
  tg: { name: 'Togo' },
  to: { name: 'Tonga' },
  tt: { name: 'Trinidad and Tobago' },
  tn: { name: 'Tunisia' },
  tr: { name: 'Turkey' },
  tm: { name: 'Turkmenistan' },
  tv: { name: 'Tuvalu' },
  ug: { name: 'Uganda' },
  ua: { name: 'Ukraine' },
  ae: { name: 'United Arab Emirates' },
  gb: { name: 'United Kingdom' },
  us: { name: 'United States' },
  uy: { name: 'Uruguay' },
  uz: { name: 'Uzbekistan' },
  vu: { name: 'Vanuatu' },
  va: { name: 'Vatican City' },
  ve: { name: 'Venezuela' },
  vn: { name: 'Vietnam' },
  ye: { name: 'Yemen' },
  zm: { name: 'Zambia' },
  zw: { name: 'Zimbabwe' },
}
