// --- Enums ------------------------------------

/**
 * @typedef {'af'|'ax'|'al'|'dz'|'as'|'ad'|'ao'|'ai'|'aq'|'ag'|'ar'|'am'|'aw'|'au'|'at'|'az'|'bs'|'bh'|'bd'|'bb'|'by'|'be'|'bz'|
 *  'bj'|'bm'|'bt'|'bo'|'bq'|'ba'|'bw'|'br'|'vg'|'bn'|'bg'|'bf'|'bi'|'cv'|'kh'|'cm'|'ca'|'ky'|'cf'|'td'|'cl'|'cn'|'cx'|
 *  'cc'|'co'|'km'|'cg'|'ck'|'cr'|'ci'|'hr'|'cu'|'cw'|'cy'|'cz'|'cd'|'dk'|'dj'|'dm'|'do'|'ec'|'eg'|'sv'|'gq'|'er'|'ee'|
 *  'sz'|'et'|'fk'|'fo'|'fj'|'fi'|'fr'|'gf'|'pf'|'tf'|'ga'|'gm'|'ge'|'de'|'gh'|'gi'|'gr'|'gl'|'gd'|'gp'|'gu'|'gt'|'gg'|
 *  'gn'|'gw'|'gy'|'ht'|'hm'|'hn'|'hk'|'hu'|'is'|'in'|'id'|'ir'|'iq'|'ie'|'im'|'il'|'it'|'jm'|'jp'|'je'|'jo'|'kz'|'ke'|
 *  'ki'|'kw'|'kg'|'la'|'lv'|'lb'|'ls'|'lr'|'ly'|'li'|'lt'|'lu'|'mo'|'mg'|'mw'|'my'|'mv'|'ml'|'mt'|'mh'|'mq'|'mr'|'mu'|
 *  'yt'|'mx'|'fm'|'md'|'mc'|'mn'|'me'|'ms'|'ma'|'mz'|'mm'|'na'|'nr'|'np'|'nl'|'nc'|'nz'|'ni'|'ne'|'ng'|'nu'|'nf'|'kp'|
 *  'mk'|'mp'|'no'|'om'|'pk'|'pw'|'pa'|'pg'|'py'|'pe'|'ph'|'pn'|'pl'|'pt'|'pr'|'qa'|'re'|'ro'|'ru'|'rw'|'bl'|'sh'|'kn'|
 *  'lc'|'mf'|'pm'|'vc'|'ws'|'sm'|'st'|'sa'|'sn'|'rs'|'sc'|'sl'|'sg'|'sx'|'sk'|'si'|'sb'|'so'|'za'|'gs'|'kr'|'ss'|'es'|
 *  'lk'|'sd'|'sr'|'sj'|'se'|'ch'|'sy'|'tw'|'tj'|'tz'|'th'|'tl'|'tg'|'tk'|'to'|'tt'|'tn'|'tr'|'tm'|'tc'|'tv'|'ug'|'ua'|
 *  'ae'|'gb'|'us'|'um'|'uy'|'vi'|'uz'|'vu'|'va'|'ve'|'vn'|'wf'|'eh'|'ye'|'zm'|'zw'} Country
 * @typedef {'nzd'|'aud'|'usd'|'gbp'|'btc'|'aed'|'ars'|'bdt'|'bhd'|'brl'|'cad'|'chf'|'clp'|'cny'|'cop'|'czk'|'dkk'|'egp'|'eur'|
 *  'hkd'|'huf'|'idr'|'ils'|'inr'|'jod'|'jpy'|'kes'|'krw'|'kwd'|'lkr'|'mad'|'mxn'|'myr'|'ngn'|'nok'|'omr'|'pen'|'php'|'pkr'|
 *  'pln'|'qar'|'ron'|'rub'|'sar'|'sek'|'sgd'|'thb'|'try'|'twd'|'uah'|'vnd'|'zar'} Currency
 */

/** @type {{ [key in Currency]: { name: string, symbol: string, digits: number, flag: string } }} */
export const currencies = {
  nzd: { name: 'New Zealand Dollar', symbol: '$', digits: 2, flag: '🇳🇿' },
  aud: { name: 'Australian Dollar', symbol: '$', digits: 2, flag: '🇦🇺' },
  usd: { name: 'US Dollar', symbol: '$', digits: 2, flag: '🇺🇸' },
  gbp: { name: 'Great Britain Pound', symbol: '£', digits: 2, flag: '🇬🇧' },
  btc: { name: 'Bitcoin', symbol: '₿', digits: 8, flag: '🌐' },
  aed: { name: 'UAE Dirham', symbol: 'د.إ', digits: 2, flag: '🇦🇪' },
  ars: { name: 'Argentine Peso', symbol: '$', digits: 2, flag: '🇦🇷' },
  bdt: { name: 'Bangladeshi Taka', symbol: '৳', digits: 2, flag: '🇧🇩' },
  bhd: { name: 'Bahraini Dinar', symbol: '.د.ب', digits: 3, flag: '🇧🇭' },
  brl: { name: 'Brazilian Real', symbol: 'R$', digits: 2, flag: '🇧🇷' },
  cad: { name: 'Canadian Dollar', symbol: '$', digits: 2, flag: '🇨🇦' },
  chf: { name: 'Swiss Franc', symbol: 'Fr', digits: 2, flag: '🇨🇭' },
  clp: { name: 'Chilean Peso', symbol: '$', digits: 0, flag: '🇨🇱' },
  cny: { name: 'Chinese Yuan', symbol: '¥', digits: 2, flag: '🇨🇳' },
  cop: { name: 'Colombian Peso', symbol: '$', digits: 2, flag: '🇨🇴' },
  czk: { name: 'Czech Koruna', symbol: 'Kč', digits: 2, flag: '🇨🇿' },
  dkk: { name: 'Danish Krone', symbol: 'kr', digits: 2, flag: '🇩🇰' },
  egp: { name: 'Egyptian Pound', symbol: '£', digits: 2, flag: '🇪🇬' },
  eur: { name: 'Euro', symbol: '€', digits: 2, flag: '🇪🇺' },
  hkd: { name: 'Hong Kong Dollar', symbol: '$', digits: 2, flag: '🇭🇰' },
  huf: { name: 'Hungarian Forint', symbol: 'Ft', digits: 0, flag: '🇭🇺' },
  idr: { name: 'Indonesian Rupiah', symbol: 'Rp', digits: 0, flag: '🇮🇩' },
  ils: { name: 'Israeli Shekel', symbol: '₪', digits: 2, flag: '🇮🇱' },
  inr: { name: 'Indian Rupee', symbol: '₹', digits: 2, flag: '🇮🇳' },
  jod: { name: 'Jordanian Dinar', symbol: 'د.ا', digits: 3, flag: '🇯🇴' },
  jpy: { name: 'Japanese Yen', symbol: '¥', digits: 0, flag: '🇯🇵' },
  kes: { name: 'Kenyan Shilling', symbol: 'Sh', digits: 2, flag: '🇰🇪' },
  krw: { name: 'South Korean Won', symbol: '₩', digits: 0, flag: '🇰🇷' },
  kwd: { name: 'Kuwaiti Dinar', symbol: 'د.ك', digits: 3, flag: '🇰🇼' },
  lkr: { name: 'Sri Lankan Rupee', symbol: 'Rs', digits: 2, flag: '🇱🇰' },
  mad: { name: 'Moroccan Dirham', symbol: 'د.م.', digits: 2, flag: '🇲🇦' },
  mxn: { name: 'Mexican Peso', symbol: '$', digits: 2, flag: '🇲🇽' },
  myr: { name: 'Malaysian Ringgit', symbol: 'RM', digits: 2, flag: '🇲🇾' },
  ngn: { name: 'Nigerian Naira', symbol: '₦', digits: 2, flag: '🇳🇬' },
  nok: { name: 'Norwegian Krone', symbol: 'kr', digits: 2, flag: '🇳🇴' },
  omr: { name: 'Omani Rial', symbol: '﷼', digits: 3, flag: '🇴🇲' },
  pen: { name: 'Peruvian Sol', symbol: 'S/', digits: 2, flag: '🇵🇪' },
  php: { name: 'Philippine Peso', symbol: '₱', digits: 2, flag: '🇵🇭' },
  pkr: { name: 'Pakistani Rupee', symbol: '₨', digits: 2, flag: '🇵🇰' },
  pln: { name: 'Polish Zloty', symbol: 'zł', digits: 2, flag: '🇵🇱' },
  qar: { name: 'Qatari Riyal', symbol: '﷼', digits: 2, flag: '🇶🇦' },
  ron: { name: 'Romanian Leu', symbol: 'lei', digits: 2, flag: '🇷🇴' },
  rub: { name: 'Russian Ruble', symbol: '₽', digits: 2, flag: '🇷🇺' },
  sar: { name: 'Saudi Riyal', symbol: '﷼', digits: 2, flag: '🇸🇦' },
  sek: { name: 'Swedish Krona', symbol: 'kr', digits: 2, flag: '🇸🇪' },
  sgd: { name: 'Singapore Dollar', symbol: '$', digits: 2, flag: '🇸🇬' },
  thb: { name: 'Thai Baht', symbol: '฿', digits: 2, flag: '🇹🇭' },
  try: { name: 'Turkish Lira', symbol: '₺', digits: 2, flag: '🇹🇷' },
  twd: { name: 'New Taiwan Dollar', symbol: 'NT$', digits: 2, flag: '🇹🇼' },
  uah: { name: 'Ukrainian Hryvnia', symbol: '₴', digits: 2, flag: '🇺🇦' },
  vnd: { name: 'Vietnamese Dong', symbol: '₫', digits: 0, flag: '🇻🇳' },
  zar: { name: 'South African Rand', symbol: 'R', digits: 2, flag: '🇿🇦' },
}

/** @type {{ [key in Country]: { name: string, flag: string } }} */
export const countries = {
  af: { name: 'Afghanistan', flag: '🇦🇫' },
  ax: { name: 'Aland Islands', flag: '🇦🇽' },
  al: { name: 'Albania', flag: '🇦🇱' },
  dz: { name: 'Algeria', flag: '🇩🇿' },
  as: { name: 'American Samoa', flag: '🇦🇸' },
  ad: { name: 'Andorra', flag: '🇦🇩' },
  ao: { name: 'Angola', flag: '🇦🇴' },
  ai: { name: 'Anguilla', flag: '🇦🇮' },
  aq: { name: 'Antarctica', flag: '🇦🇶' },
  ag: { name: 'Antigua and Barbuda', flag: '🇦🇬' },
  ar: { name: 'Argentina', flag: '🇦🇷' },
  am: { name: 'Armenia', flag: '🇦🇲' },
  aw: { name: 'Aruba', flag: '🇦🇼' },
  au: { name: 'Australia', flag: '🇦🇺' },
  at: { name: 'Austria', flag: '🇦🇹' },
  az: { name: 'Azerbaijan', flag: '🇦🇿' },
  bs: { name: 'Bahamas', flag: '🇧🇸' },
  bh: { name: 'Bahrain', flag: '🇧🇭' },
  bd: { name: 'Bangladesh', flag: '🇧🇩' },
  bb: { name: 'Barbados', flag: '🇧🇧' },
  by: { name: 'Belarus', flag: '🇧🇾' },
  be: { name: 'Belgium', flag: '🇧🇪' },
  bz: { name: 'Belize', flag: '🇧🇿' },
  bj: { name: 'Benin', flag: '🇧🇯' },
  bm: { name: 'Bermuda', flag: '🇧🇲' },
  bt: { name: 'Bhutan', flag: '🇧🇹' },
  bo: { name: 'Bolivia', flag: '🇧🇴' },
  bq: { name: 'Bonaire, Sint Eustatius and Saba', flag: '🇧🇶' },
  ba: { name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  bw: { name: 'Botswana', flag: '🇧🇼' },
  br: { name: 'Brazil', flag: '🇧🇷' },
  vg: { name: 'British Virgin Islands', flag: '🇻🇬' },
  bn: { name: 'Brunei', flag: '🇧🇳' },
  bg: { name: 'Bulgaria', flag: '🇧🇬' },
  bf: { name: 'Burkina Faso', flag: '🇧🇫' },
  bi: { name: 'Burundi', flag: '🇧🇮' },
  cv: { name: 'Cabo Verde', flag: '🇨🇻' },
  kh: { name: 'Cambodia', flag: '🇰🇭' },
  cm: { name: 'Cameroon', flag: '🇨🇲' },
  ca: { name: 'Canada', flag: '🇨🇦' },
  ky: { name: 'Cayman Islands', flag: '🇰🇾' },
  cf: { name: 'Central African Republic', flag: '🇨🇫' },
  td: { name: 'Chad', flag: '🇹🇩' },
  cl: { name: 'Chile', flag: '🇨🇱' },
  cn: { name: 'China', flag: '🇨🇳' },
  cx: { name: 'Christmas Island', flag: '🇨🇽' },
  cc: { name: 'Cocos (Keeling) Islands', flag: '🇨🇨' },
  co: { name: 'Colombia', flag: '🇨🇴' },
  km: { name: 'Comoros', flag: '🇰🇲' },
  cg: { name: 'Congo (Congo-Brazzaville)', flag: '🇨🇬' },
  ck: { name: 'Cook Islands', flag: '🇨🇰' },
  cr: { name: 'Costa Rica', flag: '🇨🇷' },
  ci: { name: "Cote d'Ivoire", flag: '🇨🇮' },
  hr: { name: 'Croatia', flag: '🇭🇷' },
  cu: { name: 'Cuba', flag: '🇨🇺' },
  cw: { name: 'Curacao', flag: '🇨🇼' },
  cy: { name: 'Cyprus', flag: '🇨🇾' },
  cz: { name: 'Czechia', flag: '🇨🇿' },
  cd: { name: 'Democratic Republic of the Congo', flag: '🇨🇩' },
  dk: { name: 'Denmark', flag: '🇩🇰' },
  dj: { name: 'Djibouti', flag: '🇩🇯' },
  dm: { name: 'Dominica', flag: '🇩🇲' },
  do: { name: 'Dominican Republic', flag: '🇩🇴' },
  ec: { name: 'Ecuador', flag: '🇪🇨' },
  eg: { name: 'Egypt', flag: '🇪🇬' },
  sv: { name: 'El Salvador', flag: '🇸🇻' },
  gq: { name: 'Equatorial Guinea', flag: '🇬🇶' },
  er: { name: 'Eritrea', flag: '🇪🇷' },
  ee: { name: 'Estonia', flag: '🇪🇪' },
  sz: { name: 'Eswatini', flag: '🇸🇿' },
  et: { name: 'Ethiopia', flag: '🇪🇹' },
  fk: { name: 'Falkland Islands', flag: '🇫🇰' },
  fo: { name: 'Faroe Islands', flag: '🇫🇴' },
  fj: { name: 'Fiji', flag: '🇫🇯' },
  fi: { name: 'Finland', flag: '🇫🇮' },
  fr: { name: 'France', flag: '🇫🇷' },
  gf: { name: 'French Guiana', flag: '🇬🇫' },
  pf: { name: 'French Polynesia', flag: '🇵🇫' },
  tf: { name: 'French Southern Territories', flag: '🇹🇫' },
  ga: { name: 'Gabon', flag: '🇬🇦' },
  gm: { name: 'Gambia', flag: '🇬🇲' },
  ge: { name: 'Georgia', flag: '🇬🇪' },
  de: { name: 'Germany', flag: '🇩🇪' },
  gh: { name: 'Ghana', flag: '🇬🇭' },
  gi: { name: 'Gibraltar', flag: '🇬🇮' },
  gr: { name: 'Greece', flag: '🇬🇷' },
  gl: { name: 'Greenland', flag: '🇬🇱' },
  gd: { name: 'Grenada', flag: '🇬🇩' },
  gp: { name: 'Guadeloupe', flag: '🇬🇵' },
  gu: { name: 'Guam', flag: '🇬🇺' },
  gt: { name: 'Guatemala', flag: '🇬🇹' },
  gg: { name: 'Guernsey', flag: '🇬🇬' },
  gn: { name: 'Guinea', flag: '🇬🇳' },
  gw: { name: 'Guinea-Bissau', flag: '🇬🇼' },
  gy: { name: 'Guyana', flag: '🇬🇾' },
  ht: { name: 'Haiti', flag: '🇭🇹' },
  hm: { name: 'Heard Island and McDonald Islands', flag: '🇭🇲' },
  hn: { name: 'Honduras', flag: '🇭🇳' },
  hk: { name: 'Hong Kong', flag: '🇭🇰' },
  hu: { name: 'Hungary', flag: '🇭🇺' },
  is: { name: 'Iceland', flag: '🇮🇸' },
  in: { name: 'India', flag: '🇮🇳' },
  id: { name: 'Indonesia', flag: '🇮🇩' },
  ir: { name: 'Iran', flag: '🇮🇷' },
  iq: { name: 'Iraq', flag: '🇮🇶' },
  ie: { name: 'Ireland', flag: '🇮🇪' },
  im: { name: 'Isle of Man', flag: '🇮🇲' },
  il: { name: 'Israel', flag: '🇮🇱' },
  it: { name: 'Italy', flag: '🇮🇹' },
  jm: { name: 'Jamaica', flag: '🇯🇲' },
  jp: { name: 'Japan', flag: '🇯🇵' },
  je: { name: 'Jersey', flag: '🇯🇪' },
  jo: { name: 'Jordan', flag: '🇯🇴' },
  kz: { name: 'Kazakhstan', flag: '🇰🇿' },
  ke: { name: 'Kenya', flag: '🇰🇪' },
  ki: { name: 'Kiribati', flag: '🇰🇮' },
  kw: { name: 'Kuwait', flag: '🇰🇼' },
  kg: { name: 'Kyrgyzstan', flag: '🇰🇬' },
  la: { name: 'Laos', flag: '🇱🇦' },
  lv: { name: 'Latvia', flag: '🇱🇻' },
  lb: { name: 'Lebanon', flag: '🇱🇧' },
  ls: { name: 'Lesotho', flag: '🇱🇸' },
  lr: { name: 'Liberia', flag: '🇱🇷' },
  ly: { name: 'Libya', flag: '🇱🇾' },
  li: { name: 'Liechtenstein', flag: '🇱🇮' },
  lt: { name: 'Lithuania', flag: '🇱🇹' },
  lu: { name: 'Luxembourg', flag: '🇱🇺' },
  mo: { name: 'Macao', flag: '🇲🇴' },
  mg: { name: 'Madagascar', flag: '🇲🇬' },
  mw: { name: 'Malawi', flag: '🇲🇼' },
  my: { name: 'Malaysia', flag: '🇲🇾' },
  mv: { name: 'Maldives', flag: '🇲🇻' },
  ml: { name: 'Mali', flag: '🇲🇱' },
  mt: { name: 'Malta', flag: '🇲🇹' },
  mh: { name: 'Marshall Islands', flag: '🇲🇭' },
  mq: { name: 'Martinique', flag: '🇲🇶' },
  mr: { name: 'Mauritania', flag: '🇲🇷' },
  mu: { name: 'Mauritius', flag: '🇲🇺' },
  yt: { name: 'Mayotte', flag: '🇾🇹' },
  mx: { name: 'Mexico', flag: '🇲🇽' },
  fm: { name: 'Micronesia', flag: '🇫🇲' },
  md: { name: 'Moldova', flag: '🇲🇩' },
  mc: { name: 'Monaco', flag: '🇲🇨' },
  mn: { name: 'Mongolia', flag: '🇲🇳' },
  me: { name: 'Montenegro', flag: '🇲🇪' },
  ms: { name: 'Montserrat', flag: '🇲🇸' },
  ma: { name: 'Morocco', flag: '🇲🇦' },
  mz: { name: 'Mozambique', flag: '🇲🇿' },
  mm: { name: 'Myanmar', flag: '🇲🇲' },
  na: { name: 'Namibia', flag: '🇳🇦' },
  nr: { name: 'Nauru', flag: '🇳🇷' },
  np: { name: 'Nepal', flag: '🇳🇵' },
  nl: { name: 'Netherlands', flag: '🇳🇱' },
  nc: { name: 'New Caledonia', flag: '🇳🇨' },
  nz: { name: 'New Zealand', flag: '🇳🇿' },
  ni: { name: 'Nicaragua', flag: '🇳🇮' },
  ne: { name: 'Niger', flag: '🇳🇪' },
  ng: { name: 'Nigeria', flag: '🇳🇬' },
  nu: { name: 'Niue', flag: '🇳🇺' },
  nf: { name: 'Norfolk Island', flag: '🇳🇫' },
  kp: { name: 'North Korea', flag: '🇰🇵' },
  mk: { name: 'North Macedonia', flag: '🇲🇰' },
  mp: { name: 'Northern Mariana Islands', flag: '🇲🇵' },
  no: { name: 'Norway', flag: '🇳🇴' },
  om: { name: 'Oman', flag: '🇴🇲' },
  pk: { name: 'Pakistan', flag: '🇵🇰' },
  pw: { name: 'Palau', flag: '🇵🇼' },
  pa: { name: 'Panama', flag: '🇵🇦' },
  pg: { name: 'Papua New Guinea', flag: '🇵🇬' },
  py: { name: 'Paraguay', flag: '🇵🇾' },
  pe: { name: 'Peru', flag: '🇵🇪' },
  ph: { name: 'Philippines', flag: '🇵🇭' },
  pn: { name: 'Pitcairn', flag: '🇵🇳' },
  pl: { name: 'Poland', flag: '🇵🇱' },
  pt: { name: 'Portugal', flag: '🇵🇹' },
  pr: { name: 'Puerto Rico', flag: '🇵🇷' },
  qa: { name: 'Qatar', flag: '🇶🇦' },
  re: { name: 'Reunion', flag: '🇷🇪' },
  ro: { name: 'Romania', flag: '🇷🇴' },
  ru: { name: 'Russia', flag: '🇷🇺' },
  rw: { name: 'Rwanda', flag: '🇷🇼' },
  bl: { name: 'Saint Barthelemy', flag: '🇧🇱' },
  sh: { name: 'Saint Helena', flag: '🇸🇭' },
  kn: { name: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  lc: { name: 'Saint Lucia', flag: '🇱🇨' },
  mf: { name: 'Saint Martin', flag: '🇲🇫' },
  pm: { name: 'Saint Pierre and Miquelon', flag: '🇵🇲' },
  vc: { name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  ws: { name: 'Samoa', flag: '🇼🇸' },
  sm: { name: 'San Marino', flag: '🇸🇲' },
  st: { name: 'Sao Tome and Principe', flag: '🇸🇹' },
  sa: { name: 'Saudi Arabia', flag: '🇸🇦' },
  sn: { name: 'Senegal', flag: '🇸🇳' },
  rs: { name: 'Serbia', flag: '🇷🇸' },
  sc: { name: 'Seychelles', flag: '🇸🇨' },
  sl: { name: 'Sierra Leone', flag: '🇸🇱' },
  sg: { name: 'Singapore', flag: '🇸🇬' },
  sx: { name: 'Sint Maarten', flag: '🇸🇽' },
  sk: { name: 'Slovakia', flag: '🇸🇰' },
  si: { name: 'Slovenia', flag: '🇸🇮' },
  sb: { name: 'Solomon Islands', flag: '🇸🇧' },
  so: { name: 'Somalia', flag: '🇸🇴' },
  za: { name: 'South Africa', flag: '🇿🇦' },
  gs: { name: 'South Georgia and the South Sandwich Islands', flag: '🇬🇸' },
  kr: { name: 'South Korea', flag: '🇰🇷' },
  ss: { name: 'South Sudan', flag: '🇸🇸' },
  es: { name: 'Spain', flag: '🇪🇸' },
  lk: { name: 'Sri Lanka', flag: '🇱🇰' },
  sd: { name: 'Sudan', flag: '🇸🇩' },
  sr: { name: 'Suriname', flag: '🇸🇷' },
  sj: { name: 'Svalbard and Jan Mayen', flag: '🇸🇯' },
  se: { name: 'Sweden', flag: '🇸🇪' },
  ch: { name: 'Switzerland', flag: '🇨🇭' },
  sy: { name: 'Syria', flag: '🇸🇾' },
  tw: { name: 'Taiwan', flag: '🇹🇼' },
  tj: { name: 'Tajikistan', flag: '🇹🇯' },
  tz: { name: 'Tanzania', flag: '🇹🇿' },
  th: { name: 'Thailand', flag: '🇹🇭' },
  tl: { name: 'Timor-Leste', flag: '🇹🇱' },
  tg: { name: 'Togo', flag: '🇹🇬' },
  tk: { name: 'Tokelau', flag: '🇹🇰' },
  to: { name: 'Tonga', flag: '🇹🇴' },
  tt: { name: 'Trinidad and Tobago', flag: '🇹🇹' },
  tn: { name: 'Tunisia', flag: '🇹🇳' },
  tr: { name: 'Turkey', flag: '🇹🇷' },
  tm: { name: 'Turkmenistan', flag: '🇹🇲' },
  tc: { name: 'Turks and Caicos Islands', flag: '🇹🇨' },
  tv: { name: 'Tuvalu', flag: '🇹🇻' },
  ug: { name: 'Uganda', flag: '🇺🇬' },
  ua: { name: 'Ukraine', flag: '🇺🇦' },
  ae: { name: 'United Arab Emirates', flag: '🇦🇪' },
  gb: { name: 'United Kingdom', flag: '🇬🇧' },
  us: { name: 'United States', flag: '🇺🇸' },
  um: { name: 'United States Minor Outlying Islands', flag: '🇺🇲' },
  uy: { name: 'Uruguay', flag: '🇺🇾' },
  vi: { name: 'US Virgin Islands', flag: '🇻🇮' },
  uz: { name: 'Uzbekistan', flag: '🇺🇿' },
  vu: { name: 'Vanuatu', flag: '🇻🇺' },
  va: { name: 'Vatican City', flag: '🇻🇦' },
  ve: { name: 'Venezuela', flag: '🇻🇪' },
  vn: { name: 'Vietnam', flag: '🇻🇳' },
  wf: { name: 'Wallis and Futuna', flag: '🇼🇫' },
  eh: { name: 'Western Sahara', flag: '🇪🇭' },
  ye: { name: 'Yemen', flag: '🇾🇪' },
  zm: { name: 'Zambia', flag: '🇿🇲' },
  zw: { name: 'Zimbabwe', flag: '🇿🇼' },
}
export const countryOptions = Object.entries(countries).map(([k, c]) => ({ value: /**@type {Country}*/(k), label: c.name, flag: c.flag }))
export const currencyOptions = Object.entries(currencies).map(([k, c]) => ({ value: /**@type {Currency}*/(k), label: c.name, 
  flag: c.flag }))