/**
 * --------------------------------------------------------------------------------------------------------
 * Mock Data
 * --------------------------------------------------------------------------------------------------------
 */


type Role = 'admin' | 'user'
type Status = 'active' | 'invite'

interface BaseEntity {
    id: string;
    createdAt: number;
    updatedAt: number;
}

type StateError = {
    title: string, detail: string, inner?: {
        path: string;
        message: string;
    }[];
};

interface StateErrors {
    errors: StateError[];
}

export interface UserState extends BaseEntity, StateErrors {
    id: string;
    createdAt: number;
    updatedAt: number;
    status: Status;
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    address: string;
    role: Role;
}

export const userData: UserState[] = [
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'active' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'user' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
].map((item, index) => ({ // Test
    ...item,
    phone: `Phone ${String(index)}`,
}))