import { Role, Status } from '../types/index'
import { UserState } from '../types/state'

export const userData: UserState[] = [
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'active' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'user' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
    {
        id: '',
        createdAt: Date.now(),
        updatedAt: Date.now(),
        status: 'invite' as Status,
        firstName: 'Firstname',
        lastName: 'Lastname',
        email: 'xxx@orchid.co.nz',
        phone: 'xxxxxxxxx',
        address: '10 Warkworth Rd \n Workwarth, Auchland',
        role: 'admin' as Role,
        errors: [],
    },
].map((item, index) => ({ // Test
    ...item,
    phone: `Phone ${String(index)}`,
}))